### ISSUE TITLE
Issues with multiply instances in Invoke-SQLoptimize

### ISSUE THREAD

**Issue by mooock** [NoMoreFood/Scripts#1]
I found the issue with this script using the Server name. i think the correct why of doing it would be to optimize on sqlinstance level instead. as it can be possible to both run Always one AG groups, clustered SQL, and multiply instances on same server.

to further optimize. it could save some time to use the DBAtools for query the instances and getting table information.

**Comment by NoMoreFood** [comment]
Not sure I'm sure what you're proposing specifically.  As noted in the help, "The -Server parameter specifies a SQL instance to query.  This string can be a server name or a server instance (e.g., MyServer\MyInstance).  A server name followed by a port (MyServer,1433) is also valid."

Are you proposing something like an -AllInstances flag that would hit all instances on a specified server?

**Comment by mooock** [comment]
Ok that was my suggestion. It was just confusing that it was written servername as i thought it only supported a hostname and query all databases. I tried both syntax with / and, port non of those was working. But will try again tomorrow. In dbatool they normally call it sqlinstance where it also possible to get data from pipeline

**Comment by NoMoreFood** [comment]
How did your test go?

**Comment by mooock** [comment]
Hi NoMoorfood

Sorry for the delay, have been caught up with work. But at this moment both the SQL instance Server\Instance and the Instance,port has been working fine. maybe some powershell variable has been messing up from another script.  maybe doing an alias -sqlinstance would be more logic. and cloud maybe also be build to work with pipeline from dbatools.
